/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import model.Person;
import model.Address;
import javax.swing.JOptionPane;
import model.Contact;


/**
 *
 * @author nehar
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    private Person person;
    public mainframe() {
        initComponents();
        
        this.person= new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        NUIDField = new javax.swing.JTextField();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        CollegeNameField = new javax.swing.JTextField();
        StreetNoField = new javax.swing.JTextField();
        AptNoField = new javax.swing.JTextField();
        CityField = new javax.swing.JTextField();
        ZipCodeField = new javax.swing.JTextField();
        PStreetNoField = new javax.swing.JTextField();
        PAptNoField = new javax.swing.JTextField();
        PCityField = new javax.swing.JTextField();
        PZipCodeField = new javax.swing.JTextField();
        workphonefield = new javax.swing.JTextField();
        homephonefield = new javax.swing.JTextField();
        workemailfield = new javax.swing.JTextField();
        homemailfield = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        StNo1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        AptNo1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        City1 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        ZipCode1 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        StNoP1 = new javax.swing.JLabel();
        AptNoP1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        RNUID = new javax.swing.JLabel();
        RFirstName1 = new javax.swing.JLabel();
        RLastName1 = new javax.swing.JLabel();
        RCollegeName1 = new javax.swing.JLabel();
        RStreetNo1 = new javax.swing.JLabel();
        RAptNo1 = new javax.swing.JLabel();
        RCity1 = new javax.swing.JLabel();
        RZipCode1 = new javax.swing.JLabel();
        RPStreetNo1 = new javax.swing.JLabel();
        RPAptNo1 = new javax.swing.JLabel();
        RPCity1 = new javax.swing.JLabel();
        RPZipCode1 = new javax.swing.JLabel();
        RWorkPhone1 = new javax.swing.JLabel();
        RHomePhone1 = new javax.swing.JLabel();
        RWorkMail1 = new javax.swing.JLabel();
        RHomeMail1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setAlignmentX(1.0F);
        jPanel1.setAlignmentY(1.0F);
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(35000, 35000));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 63, -1));

        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 61, -1));

        jLabel5.setText("Current Address :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 135, 257, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 1034, -1, -1));

        jLabel8.setText("NUID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 561, 154, 0));

        jLabel9.setText("CollegeName");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, -1, -1));

        jLabel12.setText("Street no:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, -1, -1));

        jLabel14.setText("Apt No:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        jLabel16.setText("City:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 212, 41, -1));

        jLabel18.setText("Zip Code:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, -1, -1));

        jLabel19.setText("Permanent Address:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 265, -1, -1));

        jLabel20.setText("Street no:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, -1, -1));

        jLabel21.setText("Apt No:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 51, 13));

        jLabel22.setText("City:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 341, 51, -1));

        jLabel23.setText("Zip Code:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 366, -1, 28));

        jLabel24.setText("work phone:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel25.setText("home phone:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel7.setText("work mail:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel26.setText("home mail:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jLabel27.setText("contact details");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        SaveBtn.setText("Submit");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        NUIDField.setText("NUID");
        NUIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NUIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 17, 71, -1));

        FirstNameField.setText("jTextField1");
        jPanel1.add(FirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 45, 71, -1));

        LastNameField.setText("jTextField1");
        jPanel1.add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 73, 71, -1));

        CollegeNameField.setText("jTextField1");
        jPanel1.add(CollegeNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 104, 71, -1));

        StreetNoField.setText("jTextField1");
        jPanel1.add(StreetNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 153, 71, -1));

        AptNoField.setText("jTextField1");
        jPanel1.add(AptNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 181, 71, -1));

        CityField.setText("jTextField1");
        jPanel1.add(CityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 209, 71, -1));

        ZipCodeField.setText("jTextField1");
        jPanel1.add(ZipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 237, 71, -1));

        PStreetNoField.setText("jTextField1");
        jPanel1.add(PStreetNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 282, 71, -1));

        PAptNoField.setText("jTextField1");
        PAptNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAptNoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PAptNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 310, 71, -1));

        PCityField.setText("jTextField1");
        PCityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCityFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PCityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 338, 71, -1));

        PZipCodeField.setText("jTextField1");
        jPanel1.add(PZipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 369, 71, -1));

        workphonefield.setText("jTextField1");
        workphonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workphonefieldActionPerformed(evt);
            }
        });
        jPanel1.add(workphonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 71, -1));
        jPanel1.add(homephonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 71, -1));

        workemailfield.setText("jTextField1");
        jPanel1.add(workemailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 71, -1));

        homemailfield.setText("jTextField1");
        jPanel1.add(homemailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 71, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel35.setText("First Name:");

        jLabel36.setText("Last Name:");

        jLabel37.setText("Current Address");

        StNo1.setText("Street No:");

        jLabel39.setText("Contact Details");

        AptNo1.setText("Apt No:");

        jLabel40.setText("NUID:");

        City1.setText("City:");

        jLabel41.setText("CollegeName:");

        ZipCode1.setText("Zip Code:");

        jLabel42.setText("Permanent Address");

        StNoP1.setText("Street No:");

        AptNoP1.setText("Apt No:");

        jLabel43.setText("City:");

        jLabel44.setText("Zip Code");

        jLabel45.setText("Work Phone:");

        jLabel46.setText("Home Phone:");

        jLabel47.setText("Work Mail:");

        jLabel49.setText("Home Mail:");

        jLabel50.setText("HUSKY CARD");

        RNUID.setText("jLabel51");

        RFirstName1.setText("jLabel51");

        RLastName1.setText("jLabel51");

        RCollegeName1.setText("jLabel51");

        RStreetNo1.setText("jLabel51");

        RAptNo1.setText("jLabel51");

        RCity1.setText("jLabel51");

        RZipCode1.setText("jLabel51");

        RPStreetNo1.setText("jLabel51");

        RPAptNo1.setText("jLabel51");

        RPCity1.setText("jLabel51");

        RPZipCode1.setText("jLabel51");

        RWorkPhone1.setText("jLabel51");

        RHomePhone1.setText("jLabel51");

        RWorkMail1.setText("jLabel51");

        RHomeMail1.setText("jLabel51");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel39)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RHomePhone1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RWorkPhone1)))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel49))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RHomeMail1)
                                    .addComponent(RWorkMail1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel42))
                            .addComponent(jLabel43))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(155, 155, 155))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RNUID))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel50)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(StNo1)
                            .addComponent(AptNo1)
                            .addComponent(City1)
                            .addComponent(ZipCode1)
                            .addComponent(StNoP1)
                            .addComponent(AptNoP1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RCollegeName1)
                            .addComponent(RStreetNo1)
                            .addComponent(RAptNo1)
                            .addComponent(RCity1)
                            .addComponent(RZipCode1)
                            .addComponent(RPStreetNo1)
                            .addComponent(RPAptNo1)
                            .addComponent(RPCity1)
                            .addComponent(RPZipCode1)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RLastName1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(RFirstName1))))
                .addGap(0, 563, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel50)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(RNUID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RFirstName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RLastName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(RCollegeName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AptNo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RStreetNo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RAptNo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(City1)
                    .addComponent(RCity1))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RZipCode1))
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StNoP1)
                    .addComponent(RPStreetNo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AptNoP1)
                    .addComponent(RPAptNo1))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(RPCity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(RPZipCode1)
                        .addGap(3, 3, 3)))
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47)
                    .addComponent(RWorkPhone1)
                    .addComponent(RWorkMail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel49)
                    .addComponent(RHomePhone1)
                    .addComponent(RHomeMail1))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String NUID= NUIDField.getText();
        String FirstName=FirstNameField.getText();
        String LastName=LastNameField.getText();
        String CollegeName=CollegeNameField.getText();
        String StreetNo=StreetNoField.getText();
        String AptNo=AptNoField.getText();
        String City=CityField.getText();
        String ZipCode=ZipCodeField.getText();
        String PStreetNo=PStreetNoField.getText();
        String PAptNo=PAptNoField.getText();
        String PCity=PCityField.getText();
        String PZipCode=PZipCodeField.getText();
        long workphone= Long.parseLong(workphonefield.getText());
     
        long homephone=Long.parseLong(homephonefield.getText());
        String workmail=workemailfield.getText();
        String homemail=homemailfield.getText();
        
        this.person.setFirstName(FirstName);
        this.person.setLastName(LastName);
        this.person.setNUID(NUID);
        this.person.setCollegeName(CollegeName);
        
        Address address = this.person.getAddress();
        address.setStreetName(StreetNo);
        address.setAptNo(AptNo);
        address.setCity(City);
        address.setZipCode(ZipCode);
        
        Address PAddress = this.person.getPermanentAddress();
        address.setStreetName(PStreetNo);
        address.setAptNo(PAptNo);
        address.setCity(PCity);
        address.setZipCode(PZipCode);
        
        Contact contact = this.person.getContact();
        contact.setPhone(homephone);
        contact.setMail(homemail);
        
        Contact workContact = this.person.getWorkContact();
        contact.setPhone(workphone);
        contact.setMail(workmail);
        
        display();
        
    }
    
    private void display(){
        NUID.setText(this.person.getNUID());
        RFirstName.setText(this.person.getFirstName());
        RLastName.setText(this.person.getLastName());
        RCollegeName.setText(this.person.getCollegeName());
        RStreetNo.setText(this.person.getAddress().getStreetName());
        RAptNo.setText(this.person.getAddress().getAptNo());
        RCity.setText(this.person.getAddress().getCity());
        RZipCode.setText(this.person.getAddress().getZipCode());
        RPStreetNo.setText(this.person.getPermanentAddress().getStreetName());
        RPAptNo.setText(this.person.getPermanentAddress().getAptNo());
        RPCity.setText(this.person.getPermanentAddress().getCity());
        RPZipCode.setText(this.person.getPermanentAddress().getZipCode());
        RWorkPhone.setText(String.valueOf(this.person.getWorkContact().getPhone()));
        RHomePhone.setText(String.valueOf(this.person.getContact().getPhone()));
        RWorkMail.setText(String.valueOf(this.person.getContact().getMail()));
        RHomeMail.setText(String.valueOf(this.person.getContact().getMail()));
      
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void NUIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDFieldActionPerformed

    private void PAptNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAptNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAptNoFieldActionPerformed

    private void PCityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCityFieldActionPerformed

    private void workphonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workphonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workphonefieldActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
        }
});
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AptNo;
    private javax.swing.JLabel AptNo1;
    private javax.swing.JTextField AptNoField;
    private javax.swing.JLabel AptNoP;
    private javax.swing.JLabel AptNoP1;
    private javax.swing.JLabel City;
    private javax.swing.JLabel City1;
    private javax.swing.JTextField CityField;
    private javax.swing.JTextField CollegeNameField;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JTextField NUID;
    private javax.swing.JTextField NUIDField;
    private javax.swing.JTextField PAptNoField;
    private javax.swing.JTextField PCityField;
    private javax.swing.JTextField PStreetNoField;
    private javax.swing.JTextField PZipCodeField;
    private javax.swing.JTextField RAptNo;
    private javax.swing.JLabel RAptNo1;
    private javax.swing.JTextField RCity;
    private javax.swing.JLabel RCity1;
    private javax.swing.JTextField RCollegeName;
    private javax.swing.JLabel RCollegeName1;
    private javax.swing.JTextField RFirstName;
    private javax.swing.JLabel RFirstName1;
    private javax.swing.JTextField RHomeMail;
    private javax.swing.JLabel RHomeMail1;
    private javax.swing.JTextField RHomePhone;
    private javax.swing.JLabel RHomePhone1;
    private javax.swing.JTextField RLastName;
    private javax.swing.JLabel RLastName1;
    private javax.swing.JLabel RNUID;
    private javax.swing.JTextField RPAptNo;
    private javax.swing.JLabel RPAptNo1;
    private javax.swing.JTextField RPCity;
    private javax.swing.JLabel RPCity1;
    private javax.swing.JTextField RPStreetNo;
    private javax.swing.JLabel RPStreetNo1;
    private javax.swing.JTextField RPZipCode;
    private javax.swing.JLabel RPZipCode1;
    private javax.swing.JTextField RStreetNo;
    private javax.swing.JLabel RStreetNo1;
    private javax.swing.JTextField RWorkMail;
    private javax.swing.JLabel RWorkMail1;
    private javax.swing.JTextField RWorkPhone;
    private javax.swing.JLabel RWorkPhone1;
    private javax.swing.JTextField RZipCode;
    private javax.swing.JLabel RZipCode1;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel StNo;
    private javax.swing.JLabel StNo1;
    private javax.swing.JLabel StNoP;
    private javax.swing.JLabel StNoP1;
    private javax.swing.JTextField StreetNoField;
    private javax.swing.JLabel ZipCode;
    private javax.swing.JLabel ZipCode1;
    private javax.swing.JTextField ZipCodeField;
    private javax.swing.JTextField homemailfield;
    private javax.swing.JTextField homephonefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField workemailfield;
    private javax.swing.JTextField workphonefield;
    // End of variables declaration//GEN-END:variables
}
